// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// Copyright 2025 Joshua Rich <joshua.rich@gmail.com>.

// SPDX-License-Identifier: 	AGPL-3.0-or-later

package input

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Show will render the input, with formcontrol and label wrappers where
// appropriate.
func (input *Props) Show(classes ...string) templ.Component {
	switch {
	case input.FormControl.enabled && input.HasLabels():
		// FormControls and Labels set.
		return input.FormControl.Show(input.Input.GetID(), input.Labels.Show(input.Input.Show(classes...)))
	case !input.FormControl.enabled && input.HasLabels():
		// Only Labels set.
		return input.Labels.Show(input.Input.Show(classes...))
	case input.FormControl.enabled && !input.HasLabels():
		// Only FormControls set.
		return input.FormControl.Show(input.Input.GetID(), input.Input.Show(classes...))
	default:
		// Neither FormControls nor Labels set.
		return input.Input.Show(classes...)
	}
}

var _ = templruntime.GeneratedTemplate
