// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// Copyright 2025 Joshua Rich <joshua.rich@gmail.com>.

// SPDX-License-Identifier: 	AGPL-3.0-or-later

package icon

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/joshuar/go-templ-daisyui/modifiers/color"
	"github.com/joshuar/go-templ-daisyui/modifiers/size"
	"strings"
)

// faStyle returns an appropriate FontAwesome style for the icon.
func (icon *Props) faStyle() string {
	switch icon.style {
	case Regular:
		return "fa-regular"
	case Solid:
		return "fa-solid"
	default:
		return "fa-solid"
	}
}

// faRelativeSize returns an appropriate FontAwesome relative size for the icon.
func (icon *Props) faSize() string {
	switch icon.relativeSize {
	case size.XSXS:
		return "fa-2xs"
	case size.XS:
		return "fa-xs"
	case size.SM:
		return "fa-sm"
	case size.LG:
		return "fa-lg"
	case size.XL:
		return "fa-xl"
	case size.XLXL:
		return "fa-2xl"
	default:
		return ""
	}
}

// BuildInfoIcon is a helper to build an icon that represents informational state.
func BuildInfoIcon(options ...Option) *Props {
	return Build("fa-circle-info")
}

// BuildSuccessIcon is a helper to build an icon that represents successful state.
func BuildSuccessIcon(options ...Option) *Props {
	return Build("fa-circle-check")
}

// BuildWarningIcon is a helper to build an icon that represents warning state.
func BuildWarningIcon(options ...Option) *Props {
	return Build("fa-circle-exclamation")
}

// BuildErrorIcon is a helper to build an icon that represents error state.
func BuildErrorIcon(options ...Option) *Props {
	return Build("fa-circle-xmark")
}

func (icon *Props) Show(classes ...string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{icon.name, icon.faStyle(),
			icon.faSize(),
			templ.KV(color.ApplyThemeColor(icon.GetThemeColor()), icon.ValidThemeColor()),
			templ.KV(color.ApplyStateColor(icon.GetStateColor()), icon.ValidStateColor()),
			templ.KV(strings.Join(classes, " "), len(classes) > 0),
		}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<i class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `display/icon/icon.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"></i>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
