// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// Copyright 2024 Joshua Rich <joshua.rich@gmail.com>.

// SPDX-License-Identifier: 	MIT

// Package mask represents a DaisyUI Mask.

//

// https://daisyui.com/components/mask/

package mask

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/joshuar/go-templ-daisyui"

const (
	MaskSquircle          Mask = "mask mask-squircle"
	MaskHeart             Mask = "mask mask-heart"
	MaskHexagon           Mask = "mask mask-hexagon"
	MaskHexagonAlt        Mask = "mask mask-hexagon-2"
	MaskDecagon           Mask = "mask mask-decagon"
	MaskPentagon          Mask = "mask mask-pentagon"
	MaskDiamond           Mask = "mask mask-diamond"
	MaskSquare            Mask = "mask mask-square"
	MaskCircle            Mask = "mask mask-circle"
	MaskParallelogram     Mask = "mask mask-parallelogram"
	MaskParallelogramAlt1 Mask = "mask mask-parallelogram-2"
	MaskParallelogramAlt2 Mask = "mask mask-parallelogram-3"
	MaskParallelogramAlt3 Mask = "mask mask-parallelogram-4"
	MaskStar              Mask = "mask mask-star"
	MaskStarAlt           Mask = "mask mask-star-2"
	MaskTriangle          Mask = "mask mask-triangle"
	MaskTriangleAlt1      Mask = "mask mask-triangle-2"
	MaskTriangleAlt2      Mask = "mask mask-triangle-3"
	MaskTriangleAlt3      Mask = "mask mask-triangle-4"
	MaskHalfLeft          Mask = "mask mask-half-1"
	MaskHalfRight         Mask = "mask mask-half-2"
)

type Mask = components.Class

// noop function so that templ generation doesn't report errors.
func maskNOOP() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
