// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// Copyright 2025 Joshua Rich <joshua.rich@gmail.com>.

// SPDX-License-Identifier: 	AGPL-3.0-or-later

package breakpoints

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/joshuar/go-templ-daisyui/modifiers/size"

// GetHiddenBreakpoint returns class values for setting the component as hidden
// equal to and above a size.
func (breakpoints *Breakpoints) GetHiddenBreakpoint() string {
	switch breakpoints.hidden {
	case size.XS:
		return "xs:hidden"
	case size.SM:
		return "sm:hidden"
	case size.MD:
		return "md:hidden"
	case size.LG:
		return "lg:hidden"
	case size.XL:
		return "xl:hidden"
	default:
		return ""
	}
}

// GetRevealedBreakpoint returns class values for setting the component as revealed
// equal to and above a size
func (breakpoints *Breakpoints) GetRevealedBreakpoint() string {
	switch breakpoints.revealed {
	case size.XS:
		return "hidden xs:flex"
	case size.SM:
		return "hidden sm:flex"
	case size.MD:
		return "hidden md:flex"
	case size.LG:
		return "hidden lg:flex"
	case size.XL:
		return "hidden xl:flex"
	default:
		return ""
	}
}

// noop function so that templ generation doesn't report errors.
func breakpointsNOOP() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
