// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// Copyright 2025 Joshua Rich <joshua.rich@gmail.com>.

// SPDX-License-Identifier: 	AGPL-3.0-or-later

package toggle

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/joshuar/go-templ-daisyui/modifiers/size"
import "github.com/joshuar/go-templ-daisyui/modifiers/color"
import "github.com/joshuar/go-templ-daisyui/modifiers/state"

func (toggle *Props) applySize() string {
	switch toggle.size {
	case size.XS:
		return "toggle-xs"
	case size.SM:
		return "toggle-sm"
	case size.MD:
		return "toggle-md"
	case size.LG:
		return "toggle-lg"
	case size.XL:
		return "toggle-xl"
	default:
		return "toggle-md"
	}
}

// applyThemeColor applies a theme color to the Component.
func (toggle *Props) applyThemeColor() string {
	themeColor := "toggle-neutral"

	switch toggle.GetThemeColor() {
	case color.Primary:
		themeColor = "toggle-primary"
	case color.Secondary:
		themeColor = "toggle-secondary"
	case color.Accent:
		themeColor = "toggle-accent"
	case color.Neutral:
		themeColor = "toggle-neutral"
	case color.Ghost:
		themeColor = "toggle-ghost"
	}

	return themeColor
}

// applyStateColor applies a state color to the Component.
func (toggle *Props) applyStateColor() string {
	var stateColor string

	switch toggle.GetStateColor() {
	case state.Info:
		stateColor = "toggle-info"
	case state.Success:
		stateColor = "toggle-sucess"
	case state.Warning:
		stateColor = "toggle-warning"
	case state.Error:
		stateColor = "toggle-error"
	}

	return stateColor
}

func (toggle *Props) Show() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{"toggle",
			templ.KV(toggle.applyThemeColor(), toggle.ValidThemeColor()),
			templ.KV(toggle.applyStateColor(), toggle.ValidStateColor()),
			templ.KV(toggle.applySize(), toggle.size.Valid())}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<toggle type=\"checkbox\" class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `input/toggle/toggle.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if toggle.disabled {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " disabled")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, toggle.ShowAttributes())
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "></toggle>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
