// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// Copyright 2025 Joshua Rich <joshua.rich@gmail.com>.

// SPDX-License-Identifier: 	AGPL-3.0-or-later

package loading

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/joshuar/go-templ-daisyui/modifiers/size"
import "github.com/joshuar/go-templ-daisyui/modifiers/color"
import "github.com/joshuar/go-templ-daisyui/modifiers/state"

// sizeModifier returns the size modifier of the Loading component.
func (loading *Props) applySize() string {
	switch loading.size {
	case size.XS:
		return "loading-xs"
	case size.SM:
		return "loading-sm"
	case size.MD:
		return "loading-md"
	case size.LG:
		return "loading-lg"
	case size.XL:
		return "loading-xl"
	default:
		return "loading-md"
	}
}

func (loading *Props) applyThemeColor() string {
	switch loading.GetThemeColor() {
	case color.Primary:
		return "loading-primary"
	case color.Secondary:
		return "loading-secondary"
	case color.Accent:
		return "loading-accent"
	case color.Neutral:
		return "loading-neutral"
	case color.Ghost:
		return "loading-ghost"
	default:
		return "loading-neutral"
	}
}

func (loading *Props) applyStateColor() string {
	switch loading.GetStateColor() {
	case state.Info:
		return "loading-info"
	case state.Success:
		return "loading-success"
	case state.Warning:
		return "loading-warning"
	case state.Error:
		return "loading-error"
	default:
		return "loading-success"
	}
}

// applyStyle applies the loading style.
func (loading *Props) applyStyle() string {
	switch loading.style {
	case Ball:
		return "loading-ball"
	case Bars:
		return "loading-bars"
	case Dots:
		return "loading-dots"
	case Infinity:
		return "loading-infinity"
	case Ring:
		return "loading-ring"
	case Spinner:
		return "loading-spinner"
	default:
		return "loading-spinner"
	}
}

func (loading *Props) Show() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{"loading",
			loading.applyStyle(),
			templ.KV("htmx-indicator", loading.htmxIndicator),
			templ.KV(loading.applySize(), loading.size.Valid()),
			templ.KV(loading.applyThemeColor(), loading.ValidThemeColor()),
			templ.KV(loading.applyStateColor(), loading.ValidStateColor())}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<span class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `feedback/loading/loading.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, loading.ShowAttributes())
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "></span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
