// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// Copyright 2025 Joshua Rich <joshua.rich@gmail.com>.

// SPDX-License-Identifier: 	AGPL-3.0-or-later

package text

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"github.com/joshuar/go-templ-daisyui"
	"io"
)

const (
	Italic Style = "italic"
)

// Text Style.
type Style = components.Class

const (
	Base Size = "text-base"
	XS   Size = "text-xs"
	SM   Size = "text-sm"
	LG   Size = "text-lg"
	XL   Size = "text-xl"
	XLXL Size = "text-xlxl"
)

// Size controls the font size of the text.
//
// https://tailwindcss.com/docs/font-size
type Size = components.Class

const (
	Normal     Weight = "font-normal"
	Thin       Weight = "font-thin"
	Extralight Weight = "font-extralight"
	Light      Weight = "font-light"
	Medium     Weight = "font-medium"
	Semibold   Weight = "font-semibold"
	Bold       Weight = "font-bold"
	Extrabold  Weight = "font-extrabold"
	Black      Weight = "font-black"
)

// Weight controls the font weight of the text.
//
// https://tailwindcss.com/docs/font-weight
type Weight = components.Class

const (
	Primary   Color = "text-primary"
	Secondary Color = "text-secondary"
	Accent    Color = "text-accent"
	Neutral   Color = "text-neutral"
	Info      Color = "text-info"
	Success   Color = "text-success"
	Warning   Color = "text-warning"
	Error     Color = "text-error"
)

// Color controls the text color.
type Color = components.Class

const (
	Truncate Overflow = "truncate"
	Ellipsis Overflow = "text-ellipsis"
	Clip     Overflow = "text-clip"
)

// Overflow controls how the text will overflow.
//
// https://tailwindcss.com/docs/text-overflow
type Overflow = components.Class

func (text *Props) Template() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{text.classes.Show()}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<p class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `display/text/text.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, text.attributes.ShowAttributes())
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func (text *Props) Render(ctx context.Context, w io.Writer) error {
	return text.Template().Render(ctx, w)
}

var _ = templruntime.GeneratedTemplate
